### ISSUE TITLE
[1.18.2] Tofubook doesn't seem to work.

### ISSUE THREAD

**Issue by Collecter128** [baguchan/TofuCraftReload-Recode#24]
Once I crafted it, there was just an error statement about hard tofu or something like that.

**Comment by ghost** [comment]
1.19.2
![QQ截图20230209165124](https://user-images.githubusercontent.com/83486178/217763203-9067c91c-d1e8-41cc-8206-76a476f382da.png)
![QQ截图20230209165115](https://user-images.githubusercontent.com/83486178/217763212-4fac9286-46ef-4b3d-9c18-f65aeff1deee.png)

**Comment by baguchi** [comment]
fixed in 1.19.2-2.9.3.0!
sorry for late
