### ISSUE TITLE
Can't use crafting terminal of Applied Energistics 2 with TofuCraftReload

### ISSUE THREAD

**Issue by yoshi0123** [baguchan/TofuCraftReload-Recode#25]
Crafted items disappear when craft items with using crafting terminal from AE2

`forge-1.19.2-forge-43.2.0`
`appliedenergistics2-forge-12.9.2`
`TofuCraftReload-1.19-2.3.6.0`

Latest log: https://gist.github.com/yoshi0123/4fe4c98dd51da4fcfaceb6b2e9eec2b1

Issue on AE2 Git: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6927

**Comment by baguchi** [comment]
fix in the 1.19.2-2.9.3.1!
If still has Issues tell me!
