### ISSUE TITLE
1.20.1打开古城的箱子会使服务器崩溃

### ISSUE THREAD

**Issue by Js23333** [baguchan/TofuCraftReload-Recode#30]
1.20.1打开古城箱子会让服务器崩溃，崩溃日志指出是豆腐工艺的问题，稳定复现
[crash-2023-07-11_11.18.20-server.txt](https://github.com/baguchan/TofuCraftReload-Recode/files/12010564/crash-2023-07-11_11.18.20-server.txt)

**Comment by baguchi** [comment]
fixed in newer version
you should try again with newer version
