### ISSUE TITLE
1.20.1　ネギマを食べるとボウルが手に入る

### ISSUE THREAD

**Issue by skyies618** [baguchan/TofuCraftReload-Recode#32]
Version:1.20.1-5.6.0.3

「ネギマ」を食べるとボウルが手に入ります。
棒ではないのでしょうか？

When I eat "Negima", I get a bowl.
Isn't it a stick?

**Comment by baguchi** [comment]
本来は棒ですね
直しておきます

**Comment by baguchi** [comment]
修正しときました！
