### ISSUE TITLE
1.20.1 发现两个问题

### ISSUE THREAD

**Issue by CNSnowCat** [baguchan/TofuCraftReload-Recode#37]
mod版本 5.8.3.1
骑乘豆腐猪需要使用胡萝卜钓竿而不是毛豆泥钓竿
豆腐工作站gui无法正常显示

**Comment by baguchi** [comment]
If use zunda mushroom with stick. need tofu pig make to zunda(actually make tofu pig eat zunda tofu)

**Comment by baguchi** [comment]
also fixed gui next version!
