### ISSUE TITLE
1.20.1: Server crashes when generating some chunks

### ISSUE THREAD

**Issue by FrozenGalaxy** [baguchan/TofuCraftReload-Recode#40]
java.lang.NullPointerException: No data is present for column: [5, 3]
Crash report says tofu could be related, but radium too i guess

Crash report: https://gist.github.com/FrozenGalaxy/b93c95f567d9f44c514906587aca7232

**Comment by baguchi** [comment]
looks like radium bug about poi related
try again with out radium

**Comment by FrozenGalaxy** [comment]
You are correct! I tested again and it is radium, thanks and sorry for disturbing
