### ISSUE TITLE
Error if use 5.10.0.0+ non [a-z0-9/._-] character in path of location

### ISSUE THREAD

**Issue by yaroslav4167** [baguchan/TofuCraftReload-Recode#41]
If i use TofuCraftReload 5.9.0.2 - i don't reproduce this error. 

Error message if i try to join server world:
translation{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: reate:crafting/appliances/schedule_clear mcwpaths:andesite_windmill_weave'mcwfurnitures:stripped_sp

![image](https://github.com/baguchan/TofuCraftReload-Recode/assets/18057310/27b1b834-8ee1-4d02-a5ad-d2a4c87ce26d)

**Comment by baguchi** [comment]
looks like another mod incompability...
well let's me check

**Comment by yaroslav4167** [comment]
I test only with one mod server-client configuration. And reproduced the same situation. The message this time is different.
![image](https://github.com/baguchan/TofuCraftReload-Recode/assets/18057310/d0c6de56-988e-4bf3-bb3f-902ed9c9ba5f)

**Comment by baguchi** [comment]
well fixed in TofuCraftReload 1.20.1-5.10.2.0!
If still happen let's me know
