### ISSUE TITLE
製塩かまどをクリックするとクラッシュする

### ISSUE THREAD

**Issue by marumaruo0o0** [baguchan/TofuCraftReload-Recode#46]
ver1.20.4でプレイしているときに、製塩かまどを使用するために右クリックすると画面がフリーズし、クラッシュする。
![スクリーンショット 2024-07-23 165809](https://github.com/user-attachments/assets/dbd9350f-34a1-4af6-b1d0-aee20b23d296)

**Comment by marumaruo0o0** [comment]
![スクリーンショット 2024-07-23 165902](https://github.com/user-attachments/assets/76497207-a4eb-48cc-b0b1-b42c73178133)

**Comment by baguchi** [comment]
報告ありがとうございます
残念ながら1.20.4へのサポートは終了また明言してるので、申し訳ないですが対応できません・・・
ご迷惑をおかけします
